# Generated by Django 5.1 on 2024-08-19 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Twix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twix',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Twix_media/'),
        ),
    ]
